In [1]:
import numpy as np

In [2]:
a21, a23 = 0.5,0.6
a32, a34 = 0.7,0.8

A = np.array([[0,0,0,0],[a21,0,a23,0],[0,a32,0,a34],[0,0,0,0]])
print(np.linalg.inv(np.eye(4)-A))

[[1.         0.         0.         0.        ]
 [0.86206897 1.72413793 1.03448276 0.82758621]
 [0.60344828 1.20689655 1.72413793 1.37931034]
 [0.         0.         0.         1.        ]]


In [3]:
A  = np.array([[0,1],[2,0]])
print(np.linalg.inv(np.eye(2)-A))

[[-1. -1.]
 [-2. -1.]]


In [4]:
def radius(A): # consistently fastest
    return np.max(np.abs(np.linalg.eigvals(A)))

In [8]:
n = 3
A_mean = 0.0*np.zeros(n**2)
A_cov = np.diag(np.ones(n**2))

for i in range(1000000):
    A = np.round(np.random.multivariate_normal(A_mean,A_cov).reshape(n,n),1)
    if radius(np.abs(A))<1:
        if not radius(A)<1:
            # Found counterexample
            print(A)
            print(radius(np.abs(A)))
            print(radius(A))