In [1]:
import numpy as np
from itertools import combinations, product
from matplotlib import pyplot as plt
from tqdm import tqdm
import time

In [15]:
def radius(A): # consistently fastest
    return np.max(np.abs(np.linalg.eigvals(A)))

def generate_intrinsic(lower,upper,n,rnd=1,seconds=60):
    start = time.time()
    while time.time() - start < seconds:
        A = np.round(np.random.uniform(lower,upper,size=(n,n)),rnd)
        if radius(np.abs(A)) < 1:
            return A
    raise ValueError("allotted time exceeded")
    
def generate_stable(lower,upper,n,rnd=1,seconds=60):
    start = time.time()
    while time.time() - start < seconds:
        A = np.round(np.random.uniform(lower,upper,size=(n,n)),rnd)
        if radius(A) < 1:
            return A
    raise ValueError("allotted time exceeded")
    
def is_uniquely_solvable(A):
    n = np.shape(A)[0]
#     return np.linalg.det(np.eye(n) - A) != 0.
    return radius(A) < 1

def is_simple(A):
    n = np.shape(A)[0]
    for k in range(1,n+1):
        for indices in combinations(range(n),k):
            if not is_uniquely_solvable(A[np.ix_(indices,indices)]):
                return False
    return True

def generate_simple(lower,upper,n,rnd=1,seconds=60):
    start = time.time()
    while time.time() - start < seconds:
        A = np.round(np.random.uniform(lower,upper,size=(n,n)),rnd)
        if is_simple(A):
            return A
    raise ValueError("allotted time exceeded")
    
# def output_minors

In [16]:
# lower, upper = -2, 2
# n = 3

# A = generate_simple(lower,upper,n,rnd=1,seconds=60)
# print(A)
# print(radius(A))
# print(radius(np.abs(A)))
# print(np.linalg.det(np.eye(n)-A))
# print(np.linalg.det(np.eye(n)-np.abs(A)))

In [21]:
# Check if linearization preserves strong simplicity (it does not)
epsilon = 1e-5

for n in range(2,5):
    print("n={}".format(n))
    time.sleep(0.5)
    for i in tqdm(range(100)):
        A = generate_simple(-2,2,n,rnd=1,seconds=600)
        for k in range(1,n):
            for indices in combinations(range(n),k):
                assert radius(A[np.ix_(indices,indices)]) < 1, (radius(A[np.ix_(indices,indices)]), radius(A))
                if not radius(np.abs(A[np.ix_(indices,indices)])) < 1:
                    assert radius(np.abs(A)) > 1

n=2


100%|██████████| 100/100 [00:00<00:00, 669.34it/s]


n=3


100%|██████████| 100/100 [00:02<00:00, 44.74it/s]


n=4


100%|██████████| 100/100 [05:37<00:00,  3.38s/it]


In [20]:
# Check if linearization preserves strong simplicity (it does not)
epsilon = 1e-5

for n in range(2,5):
    print("n={}".format(n))
    time.sleep(0.5)
    for i in tqdm(range(100)):
        A = generate_simple(-2,2,n,rnd=1,seconds=600)
        for k in range(1,n):
            for indices in combinations(range(n),k):
                assert radius(A[np.ix_(indices,indices)]) < 1, (radius(A[np.ix_(indices,indices)]), radius(A))
                assert radius(np.abs(A[np.ix_(indices,indices)])) < 1, (radius(A[np.ix_(indices,indices)]), radius(np.abs(A[np.ix_(indices,indices)])),radius(np.abs(A)))

n=2


100%|██████████| 100/100 [00:00<00:00, 788.02it/s]


n=3


  0%|          | 0/100 [00:00<?, ?it/s]


AssertionError: (0.44721359549995787, 1.084428877022476, 1.2663444442733511)

In [13]:
# # Check if linearization preserves simplicity (it does not)
# epsilon = 1e-5

# for n in range(2,5):
#     print("n={}".format(n))
#     time.sleep(0.5)
#     for i in tqdm(range(100)):
#         A = generate_simple(-2,2,n,rnd=1,seconds=600)
#         for k in range(1,n):
#             for indices in combinations(range(n),k):
#                 assert np.linalg.det(np.eye(k) - A[np.ix_(indices,indices)]) != 0.
#                 assert np.linalg.det(np.eye(k) - np.abs(A[np.ix_(indices,indices)])) != 0., (A,indices,np.linalg.det(np.eye(k) - A[np.ix_(indices,indices)]), np.linalg.det(np.eye(k) - np.abs(A[np.ix_(indices,indices)])))

n=2


 13%|█▎        | 13/100 [00:00<00:00, 1254.71it/s]


AssertionError: (array([[-0. , -0.1],
       [ 1.2, -1. ]]), (1,), 2.0, 0.0)

In [5]:
raise ValueError

ValueError: 

In [ ]:
# Verify that ...
epsilon = 1e-5

for n in range(2,5):
    print("n={}".format(n))
    time.sleep(0.5)
    for i in tqdm(range(100)):
        A = generate_simple(-2,2,n,rnd=1,seconds=600)
        for k in range(1,n):
            for indices in combinations(range(n),k):
                assert radius(A[np.ix_(indices,indices)]) <= 1 + epsilon, (radius(A[np.ix_(indices,indices)]), radius(A))

In [97]:
lower, upper = -2, 2
n = 3

B = generate_simple(lower,upper,n,rnd=1,seconds=60)
print(B)
print(radius(B))
print(radius(np.abs(B)))

A = np.abs(B)
A *= radius(B)/radius(A)

print(radius(A))

[[-0.3 -0.6 -0.1]
 [ 0.4  0.3 -0.3]
 [ 1.3 -0.5 -0.1]]
0.7369762099857852
1.1425652340447794
0.7369762099857863
